// Copyright (c) SeasonEngine and contributors.
// Licensed under the MIT License.
// https://github.com/SeasonRealms/SeasonEngine

using Silk.NET.Direct3D12;
using Silk.NET.DXGI;

namespace Season.Platforms.Windows.DirectX;

/// <summary>
/// 1-8 Compute 3D storage texture on the D3D12 backend:
/// a single-mip ResourceDimension.Texture3D resource with
/// DepthOrArraySize=depth and AllowUnorderedAccess.
/// The SRV is used for trilinear sampling
/// (s0 static sampler with clamp on all three axes), and the UAV is used for
/// compute writes. There is no upload path; contents are always generated by
/// kernels, such as Global SDF or voxel-albedo data.
///
/// It intentionally stays separate from <see cref="DXTexture"/> rather than
/// extending it, for the same reason as <see cref="DXTextureCube"/>.
/// DXTexture assumes a Texture2D single-subresource pipeline everywhere
/// (SRV dimension, footprint, copy destination, UAV, sub-rect updates), and
/// mixing in 3D would add branches to every path. More importantly, the
/// registry must stay separate. Items in Device.DictionaryDXTexture are
/// consumed by Sprite2D and materials by name, and mixing in 3D textures would
/// let those paths fetch an unsampleable dimension. Cubemaps already follow
/// this precedent in 1-7. So 3D textures cannot be shown directly by Sprite2D;
/// visualization must go through a 3D-to-2D slicing kernel.
///
/// Lifetime: Graphics.CreateComputeTexture3D uses
/// <see cref="CreateOrUpdate"/> by name. Size mismatches trigger in-place
/// recreation that reuses descriptor slots and preserves the C# object
/// identity. DispatchCompute looks up views by name through <see cref="Find"/>.
/// All state transitions are centralized in DispatchCompute:
/// write slots -> UnorderedAccess, sample slots -> AllShaderResource.
/// Sample slots use the union of non-pixel and pixel shader resource state
/// rather than only NonPixelShaderResource, because since 2-5 Step E, 3D
/// textures have had a draw-time consumer as well
/// (the aerial-perspective LUT bound at t15 in the main shader). The union
/// state makes compute-side and graphics-side sampling both idempotent.
/// Size convention: any edge longer than 256 requires a device-capability check.
/// On the VK side, maxImageDimension3D is only guaranteed to have a lower bound
/// of 256. A single SDF cascade is recommended to stay at or below 128^3.
/// </summary>
internal unsafe sealed class DXTexture3D : IDisposable
{
    public string Name = string.Empty;

    public uint Width;
    public uint Height;
    public uint Depth;

    /// <summary>The native resource plus both views are ready.
    /// Set immediately on creation, with no upload wait.</summary>
    public bool Ready;

    public int DescriptorID = -1;

    public CpuDescriptorHandle CpuDescriptorHandle;

    public GpuDescriptorHandle GpuDescriptorHandle;

    public int UavDescriptorID = -1;

    public GpuDescriptorHandle UavGpuDescriptorHandle;

    Format _format = Format.FormatR8G8B8A8Unorm;

    ID3D12Resource* _resource = null;

    ResourceStates _currentState = ResourceStates.Common;

    readonly object _stateLock = new object();

    /// <summary>Name-based registry, following the name-as-handle convention
    /// from 1-6 / 1-7. All accesses hold this lock.</summary>
    static readonly Dictionary<string, DXTexture3D> _registry = new();

    static DXTexture3D _dummyBlack;

    /// <summary>1x1x1 all-zero fallback volume.
    /// The root signature's t15 table always needs a valid descriptor because
    /// the shader statically references apLut. Bind this object when aerial
    /// perspective is not ready.
    /// It intentionally bypasses the upload path because D3D12 committed
    /// resources are zero-initialized by default unless CreateNotZeroed is
    /// requested. In the AP LUT, the alpha channel stores opacity, and zero
    /// means "nothing occluded", so an all-zero texture is the identity element
    /// of the compositing formula
    /// (see SkyAtmosphereEffect.SourceAerialHlsl for the encoding rationale).
    /// This is the real reason opacity is stored instead of transmittance:
    /// if transmittance were stored, alpha=0 here would black out the whole
    /// image. There is no UAV because it is never written, and it is not added
    /// to the registry because the effect layer must never resolve it by name.
    /// This follows the same pattern as <see cref="DXTextureCube"/>.DummyBlack.</summary>
    internal static DXTexture3D DummyBlack
    {
        get
        {
            if (_dummyBlack == null)
            {
                var tex = new DXTexture3D
                {
                    Name = "__AerialLutDummyBlack",
                    Width = 1,
                    Height = 1,
                    Depth = 1,
                    _format = Format.FormatR16G16B16A16Float,
                };
                tex.DescriptorID = Device.DescriptorAllocator.Allocate();
                tex.CpuDescriptorHandle = Device.SrvHeapManager.GetCpuHandle(tex.DescriptorID);
                tex.GpuDescriptorHandle = Device.SrvHeapManager.GetGpuHandle(tex.DescriptorID);
                tex.CreateResource();
                tex.CreateSRV();
                tex.Ready = true;
                _dummyBlack = tex;
            }
            return _dummyBlack;
        }
    }

    /// <summary>Looks up by name. Returns null when not registered.</summary>
    internal static DXTexture3D Find(string name)
    {
        if (string.IsNullOrEmpty(name))
            return null;

        lock (_registry)
        {
            return _registry.TryGetValue(name, out var tex) ? tex : null;
        }
    }

    /// <summary>
    /// Creates or updates a 3D storage texture by name.
    /// If one already exists with the same dimensions, reuse it directly.
    /// If dimensions mismatch, recreate the native resource in place while
    /// reusing the already allocated SRV/UAV descriptor slots, so the C# object
    /// identity stays unchanged and upper-layer references remain valid.
    /// The caller must guarantee the GPU is idle. On the resize path, this is
    /// driven by BaseApp.Resize after WaitForGpu.
    /// </summary>
    internal static DXTexture3D CreateOrUpdate(string name, uint width, uint height, uint depth,
        Season.Rendering.ComputeStorageFormat format)
    {
        var nativeFormat = MapFormat(format);

        lock (_registry)
        {
            if (_registry.TryGetValue(name, out var existing))
            {
                if (existing.Width == width && existing.Height == height
                    && existing.Depth == depth && existing._format == nativeFormat)
                    return existing;

                existing.Recreate(width, height, depth, nativeFormat);
                return existing;
            }

            var tex = new DXTexture3D
            {
                Name = name,
                Width = width,
                Height = height,
                Depth = depth,
                _format = nativeFormat,
            };

            tex.DescriptorID = Device.DescriptorAllocator.Allocate();
            tex.CpuDescriptorHandle = Device.SrvHeapManager.GetCpuHandle(tex.DescriptorID);
            tex.GpuDescriptorHandle = Device.SrvHeapManager.GetGpuHandle(tex.DescriptorID);

            tex.UavDescriptorID = Device.DescriptorAllocator.Allocate();
            tex.UavGpuDescriptorHandle = Device.SrvHeapManager.GetGpuHandle(tex.UavDescriptorID);

            tex.CreateResource();
            tex.CreateSRV();
            tex.CreateUAV();
            tex.Ready = true;

            _registry.Add(name, tex);
            return tex;
        }
    }

    /// <summary>
    /// 1-8 Format intent -> concrete D3D12 format.
    /// Delegates to <see cref="DXTexture.MapComputeFormat"/>, the single source
    /// of truth shared by both 2D and 3D creation paths so the same intent
    /// cannot map to different concrete formats in different places.
    /// </summary>
    internal static Format MapFormat(Season.Rendering.ComputeStorageFormat format)
        => DXTexture.MapComputeFormat(format);

    void Recreate(uint width, uint height, uint depth, Format nativeFormat)
    {
        if (_resource != null)
        {
            _resource->Release();
            _resource = null;
        }

        Width = width;
        Height = height;
        Depth = depth;
        _format = nativeFormat;

        CreateResource();
        CreateSRV();
        CreateUAV();
        Ready = true;
    }

    ResourceDesc BuildResourceDesc() => new ResourceDesc
    {
        Dimension = ResourceDimension.Texture3D,
        Alignment = 0,
        Width = Width,
        Height = Height,
        // For 3D resources this field is depth.
        // It is slice count only for cube / array resources.
        DepthOrArraySize = (ushort)Depth,
        MipLevels = 1,
        Format = _format,
        SampleDesc = new SampleDesc(1, 0),
        Layout = TextureLayout.LayoutUnknown,
        Flags = ResourceFlags.AllowUnorderedAccess,
    };

    void CreateResource()
    {
        var heapProps = new HeapProperties(HeapType.Default);
        var desc = BuildResourceDesc();

        ID3D12Resource* resource;
        var iid = ID3D12Resource.Guid;
        var result = Device.D3dDevice->CreateCommittedResource(
            &heapProps, HeapFlags.None, &desc, ResourceStates.Common, null, &iid, (void**)&resource);

        var ex = Marshal.GetExceptionForHR(result);
        if (ex != null) throw ex;

        _resource = resource;
        _currentState = ResourceStates.Common;
    }

    void CreateSRV()
    {
        const uint DefaultShader4ComponentMapping = 0x00001688;

        var srvDesc = new ShaderResourceViewDesc
        {
            Format = _format,
            ViewDimension = SrvDimension.Texture3D,
            Shader4ComponentMapping = DefaultShader4ComponentMapping,
            Texture3D = new Tex3DSrv
            {
                MipLevels = 1,
                MostDetailedMip = 0,
                ResourceMinLODClamp = 0f,
            },
        };

        Device.D3dDevice->CreateShaderResourceView(_resource, &srvDesc, CpuDescriptorHandle);
    }

    void CreateUAV()
    {
        // WSize = depth, so the UAV covers all W slices directly
        // through RWTexture3D uint3 indexing.
        var uavDesc = new UnorderedAccessViewDesc
        {
            Format = _format,
            ViewDimension = UavDimension.Texture3D,
            Texture3D = new Tex3DUav
            {
                MipSlice = 0,
                FirstWSlice = 0,
                WSize = Depth,
            },
        };

        Device.D3dDevice->CreateUnorderedAccessView(
            _resource, null, &uavDesc, Device.SrvHeapManager.GetCpuHandle(UavDescriptorID));
    }

    /// <summary>Gated state transition. Semantics match DXTexture.TransitionTo
    /// and it is driven only by DispatchCompute.</summary>
    internal void TransitionTo(ID3D12GraphicsCommandList* commandList, ResourceStates newState)
    {
        if (_resource == null)
            return;

        lock (_stateLock)
        {
            if (_currentState != newState)
            {
                var barrier = Device.InitTransition(_resource, _currentState, newState);
                commandList->ResourceBarrier(1, &barrier);
                _currentState = newState;
            }
        }
    }

    /// <summary>Graphics-side state guard before each draw bind.
    /// This takes only the state half of DXTexture.EnsureReadyForRendering
    /// because 3D textures have no upload path and therefore do not need to
    /// wait on a Copy Queue fence.
    /// Real LUTs are already in AllShaderResource after DispatchCompute, so the
    /// gated transition becomes a no-op. <see cref="DummyBlack"/> transitions
    /// once from Common on first bind and then stays there.</summary>
    internal void EnsureReadyForRendering(ID3D12GraphicsCommandList* commandList)
        => TransitionTo(commandList, ResourceStates.AllShaderResource);

    public void Dispose()
    {
        lock (_registry)
        {
            if (!string.IsNullOrEmpty(Name) && _registry.TryGetValue(Name, out var registered) && registered == this)
                _registry.Remove(Name);
        }

        if (_resource != null)
        {
            // Overwrite both views with null descriptors before Release, for the
            // same reason as DXTexture.Dispose. The Debug Layer throws an
            // SEHException if a live descriptor still points to a released resource.
            const uint DefaultShader4ComponentMapping = 0x00001688;
            var nullSrvDesc = new ShaderResourceViewDesc
            {
                Format = Format.FormatR8G8B8A8Unorm,
                ViewDimension = SrvDimension.Texture3D,
                Shader4ComponentMapping = DefaultShader4ComponentMapping,
                Texture3D = new Tex3DSrv { MipLevels = 1, MostDetailedMip = 0, ResourceMinLODClamp = 0f },
            };
            Device.D3dDevice->CreateShaderResourceView(null, &nullSrvDesc, CpuDescriptorHandle);

            if (UavDescriptorID >= 0)
            {
                var nullUavDesc = new UnorderedAccessViewDesc
                {
                    Format = Format.FormatR8G8B8A8Unorm,
                    ViewDimension = UavDimension.Texture3D,
                    Texture3D = new Tex3DUav { MipSlice = 0, FirstWSlice = 0, WSize = 1 },
                };
                Device.D3dDevice->CreateUnorderedAccessView(
                    null, null, &nullUavDesc, Device.SrvHeapManager.GetCpuHandle(UavDescriptorID));
            }

            _resource->Release();
            _resource = null;
        }

        if (UavDescriptorID >= 0)
        {
            Device.DescriptorAllocator.Free(UavDescriptorID);
            UavDescriptorID = -1;
        }

        if (DescriptorID >= 0)
        {
            Device.DescriptorAllocator.Free(DescriptorID);
            DescriptorID = -1;
        }

        Ready = false;
    }
}
