// Copyright (c) SeasonEngine and contributors.
// Licensed under the MIT License.
// https://github.com/SeasonRealms/SeasonEngine

using Silk.NET.Vulkan;
using Image = Silk.NET.Vulkan.Image;

namespace Season.Platforms.Shared.LinuxAndroid.Vulkan;

/// <summary>
/// 1-8 Compute 3D storage texture (Vulkan side):
/// a single-mip, single-layer ImageType.Type3D image with Extent{w,h,d},
/// created with StorageBit|SampledBit.
/// Its ImageViewType.Type3D view serves both compute writes
/// (StorageImage, layout General)
/// and trilinear sampling
/// (CombinedImageSampler + Pipeline.StaticSampler with ClampToEdge on all three axes).
/// There is no upload chain - contents are always generated by kernels
/// (Global SDF / voxel albedo style), so the texture is Ready immediately after creation.
///
/// It intentionally stays separate from <see cref="Texture"/> instead of extending it
/// (for the same reason as <see cref="VKTextureCube"/>):
/// the latter assumes single-layer 2D across the whole chain
/// (ViewType, BufferImageCopy, sub-rect uploads, UploadFenceValue wait chain).
/// More importantly, the registry must stay separate:
/// elements in Graphics.DictionaryVKTexture are consumed by Sprite2D/material paths by name,
/// and mixing 3D textures in would hand those paths an unsampleable dimension
/// (the 1-7 cubemap path already established this precedent).
/// Therefore 3D textures cannot be displayed directly by Sprite2D;
/// visualization must go through a 3D -> 2D slicing kernel.
///
/// Lifetime:
/// Graphics.CreateComputeTexture3D resolves by name through <see cref="CreateOrUpdate"/>
/// (dimension/format mismatch triggers in-place recreation while preserving C# object identity),
/// DispatchCompute resolves views by name through <see cref="Find"/>,
/// and all layout flow is centralized in DispatchCompute
/// (write slot -> General, sampled slot -> ShaderReadOnlyOptimal).
/// Barriers are always recorded outside render passes
/// (Android tiler restriction; see the "no barriers inside pass bodies" rule at the top of Device).
///
/// Size contract:
/// Vulkan only guarantees a minimum of 256 for maxImageDimension3D,
/// so any dimension > 256 must first query device capabilities.
/// A single SDF cascade is recommended to stay <= 128^3.
/// Format availability is pre-validated by Graphics.CheckComputeFormatSupport
/// (vkGetPhysicalDeviceFormatProperties) in both CreateComputeKernel and CreateComputeTexture3D:
/// missing StorageImageBit or, for sampled slots, SampledImageFilterLinearBit
/// causes graceful degradation during registration.
/// No silent format substitution is performed,
/// because that would conflict with GLSL `layout(r16f)` qualifiers
/// (see the comment in Graphics.CheckComputeFormatSupport).
/// </summary>
internal unsafe sealed class VKTexture3D : IDisposable
{
    public string Name = string.Empty;

    public uint Width;

    public uint Height;

    public uint Depth;

    /// <summary>Native resources and the view are fully ready
    /// (set immediately on creation, with no upload wait).</summary>
    public bool Ready;

    public Image Image;

    public DeviceMemory Memory;

    public Silk.NET.Vulkan.ImageView View;

    /// <summary>Monotonically increasing identity number of the View
    /// (same semantics as Texture.ViewVersion - handles are reused by allocators,
    /// so downstream caches must compare the version, not the handle).</summary>
    public ulong ViewVersion;

    public Format Format = Silk.NET.Vulkan.Format.R8G8B8A8Unorm;

    /// <summary>Current image layout, starting from Undefined
    /// and driven from a single point by DispatchCompute.</summary>
    public ImageLayout CurrentLayout = ImageLayout.Undefined;

    /// <summary>Name-based registry (name-as-handle, same convention as 1-6/1-7).
    /// All access is protected by this lock.</summary>
    static readonly Dictionary<string, VKTexture3D> _registry = new();

    /// <summary>2-5 Step E: 1x1x1 all-zero fallback volume for binding 20
    /// (lazily created, same pattern as VKTextureCube.DummyBlack, and not registered).
    /// GLSL statically references `aerialLut`, so a bindable descriptor must exist even when not ready.
    /// All zero is exactly the identity element of the additive composition formula
    /// (`a` here is opacity, not transmittance).
    /// apParams0.x gating guarantees the dummy is never sampled when bound,
    /// so the content itself is never evaluated.
    /// However, the layout must start as ShaderReadOnlyOptimal to satisfy the descriptor declaration.
    /// (Mirrors DXTexture3D.DummyBlack.)</summary>
    static VKTexture3D? _dummyBlack;

    internal static VKTexture3D DummyBlack
    {
        get
        {
            if (_dummyBlack == null)
                _dummyBlack = CreateDummyBlack();
            return _dummyBlack;
        }
    }

    static VKTexture3D CreateDummyBlack()
    {
        var tex = new VKTexture3D
        {
            Name = "__AerialLutDummyBlack",
            Width = 1,
            Height = 1,
            Depth = 1,
            Format = Silk.NET.Vulkan.Format.R8G8B8A8Unorm,
        };
        tex.CreateImageResource(ImageLayout.ShaderReadOnlyOptimal);
        tex.CreateImageView();
        tex.Ready = true;
        return tex;
    }

    /// <summary>Lookup by name (returns null if not registered).</summary>
    internal static VKTexture3D? Find(string name)
    {
        if (string.IsNullOrEmpty(name))
            return null;

        lock (_registry)
        {
            return _registry.TryGetValue(name, out var tex) ? tex : null;
        }
    }

    /// <summary>
    /// Create or update a 3D storage texture by name.
    /// If an existing texture with the same name matches dimensions and format, reuse it directly;
    /// otherwise recreate native resources in place
    /// (old resources are released deferred, see <see cref="Recreate"/>).
    /// </summary>
    internal static VKTexture3D CreateOrUpdate(string name, uint width, uint height, uint depth, Format format)
    {
        lock (_registry)
        {
            if (_registry.TryGetValue(name, out var existing))
            {
                if (existing.Width == width && existing.Height == height
                    && existing.Depth == depth && existing.Format == format)
                    return existing;

                existing.Recreate(width, height, depth, format);
                return existing;
            }

            var tex = new VKTexture3D
            {
                Name = name,
                Width = width,
                Height = height,
                Depth = depth,
                Format = format,
            };
            tex.CreateImageResource();
            tex.CreateImageView();
            tex.Ready = true;

            _registry.Add(name, tex);
            return tex;
        }
    }

    /// <summary>
    /// 1-8 format intent -> Vulkan concrete format:
    /// forwarded to <see cref="Texture.MapComputeFormat"/> as the single source of truth,
    /// shared by both the 2D and 3D creation paths
    /// to prevent the same intent from mapping to different concrete formats.
    /// </summary>
    internal static Format MapComputeFormat(Season.Rendering.ComputeStorageFormat format)
        => Texture.MapComputeFormat(format);

    /// <summary>
    /// Recreate native resources (Image/Memory/View) in place to fit the new dimensions,
    /// while preserving the same C# object identity.
    ///
    /// Old resources must go through deferred release
    /// (same pattern as <see cref="Texture.RecreateComputeStorage"/>, where the real failure was documented):
    /// on mainstream implementations, VkImageView/VkImage handles are heap pointers.
    /// A "destroy then create" sequence can cause the allocator to return the exact same memory block,
    /// so old and new handle values become identical.
    /// Any downstream cache that checks invalidation by handle silently hits,
    /// leaving descriptors baked from destroyed views behind,
    /// and the GPU then reads freed memory.
    /// </summary>
    void Recreate(uint width, uint height, uint depth, Format format)
    {
        var vk = Device.Vk;
        var d = Device.LogicalDevice;

        var oldView = View; View = default;
        var oldImage = Image; Image = default;
        var oldMemory = Memory; Memory = default;
        Device.EnqueueDeferredRelease(() =>
        {
            if (oldView.Handle != 0) vk.DestroyImageView(d, oldView, null);
            if (oldImage.Handle != 0) vk.DestroyImage(d, oldImage, null);
            if (oldMemory.Handle != 0) vk.FreeMemory(d, oldMemory, null);
        });

        Width = width;
        Height = height;
        Depth = depth;
        Format = format;
        CurrentLayout = ImageLayout.Undefined;
        CreateImageResource();
        CreateImageView();
        Ready = true;
    }
    void CreateImageResource(ImageLayout initialLayout = ImageLayout.Undefined)
    {
        // There is no upload chain, so the transfer queue never participates
        // and SharingMode stays Exclusive.
        // The 2D path uses Concurrent only to avoid transfer -> graphics ownership barriers,
        // a case that does not exist here.
        // initialLayout: the dummy starts directly in ShaderReadOnlyOptimal
        // (see CreateDummyBlack).
        var info = new ImageCreateInfo
        {
            SType = StructureType.ImageCreateInfo,
            ImageType = ImageType.Type3D,
            Format = Format,
            Extent = new Extent3D(Width, Height, Depth),
            MipLevels = 1,
            ArrayLayers = 1,
            Samples = SampleCountFlags.Count1Bit,
            Tiling = ImageTiling.Optimal,
            Usage = ImageUsageFlags.StorageBit | ImageUsageFlags.SampledBit,
            SharingMode = SharingMode.Exclusive,
            InitialLayout = initialLayout,
        };

        if (Device.Vk.CreateImage(Device.LogicalDevice, in info, null, out Image) != Result.Success)
            throw new Exception($"vkCreateImage (3D '{Name}' {Width}×{Height}×{Depth} {Format}) failed");

        Device.Vk.GetImageMemoryRequirements(Device.LogicalDevice, Image, out var memReq);

        var allocInfo = new MemoryAllocateInfo
        {
            SType = StructureType.MemoryAllocateInfo,
            AllocationSize = memReq.Size,
            MemoryTypeIndex = Device.ResourceManager.FindMemoryType(
                memReq.MemoryTypeBits, MemoryPropertyFlags.DeviceLocalBit),
        };

        if (Device.Vk.AllocateMemory(Device.LogicalDevice, in allocInfo, null, out Memory) != Result.Success)
            throw new Exception($"vkAllocateMemory (3D image '{Name}') failed");

        Device.Vk.BindImageMemory(Device.LogicalDevice, Image, Memory, 0);
        CurrentLayout = initialLayout;
    }

    void CreateImageView()
    {
        var info = new ImageViewCreateInfo
        {
            SType = StructureType.ImageViewCreateInfo,
            Image = Image,
            ViewType = ImageViewType.Type3D,
            Format = Format,
            Components = new ComponentMapping(
                ComponentSwizzle.Identity, ComponentSwizzle.Identity,
                ComponentSwizzle.Identity, ComponentSwizzle.Identity),
            SubresourceRange = new ImageSubresourceRange
            {
                AspectMask = ImageAspectFlags.ColorBit,
                BaseMipLevel = 0,
                LevelCount = 1,
                BaseArrayLayer = 0,
                LayerCount = 1,
            },
        };

        if (Device.Vk.CreateImageView(Device.LogicalDevice, in info, null, out View) != Result.Success)
            throw new Exception($"vkCreateImageView (3D '{Name}') failed");

        ViewVersion = Device.NextViewVersion();
    }

    /// <summary>Gated layout transition
    /// (same semantics as <see cref="Texture.TransitionTo"/>; driven from a single point by DispatchCompute,
    /// and always recorded outside render passes).</summary>
    public void TransitionTo(CommandBuffer cmd, ImageLayout newLayout,
        PipelineStageFlags srcStage, PipelineStageFlags dstStage,
        AccessFlags srcAccess, AccessFlags dstAccess)
    {
        if (CurrentLayout == newLayout) return;

        var barrier = new ImageMemoryBarrier
        {
            SType = StructureType.ImageMemoryBarrier,
            OldLayout = CurrentLayout,
            NewLayout = newLayout,
            SrcQueueFamilyIndex = Vk.QueueFamilyIgnored,
            DstQueueFamilyIndex = Vk.QueueFamilyIgnored,
            Image = Image,
            SubresourceRange = new ImageSubresourceRange
            {
                AspectMask = ImageAspectFlags.ColorBit,
                BaseMipLevel = 0,
                LevelCount = 1,
                BaseArrayLayer = 0,
                LayerCount = 1,
            },
            SrcAccessMask = srcAccess,
            DstAccessMask = dstAccess,
        };

        Device.Vk.CmdPipelineBarrier(cmd, srcStage, dstStage, 0, 0, null, 0, null, 1, in barrier);
        CurrentLayout = newLayout;
    }

    public void Dispose()
    {
        lock (_registry)
        {
            if (!string.IsNullOrEmpty(Name) && _registry.TryGetValue(Name, out var registered)
                && ReferenceEquals(registered, this))
                _registry.Remove(Name);
        }

        var vk = Device.Vk;
        var d = Device.LogicalDevice;
        var view = View; View = default;
        var image = Image; Image = default;
        var memory = Memory; Memory = default;
        Ready = false;

        // In-flight command buffers may still reference this texture,
        // so destruction must wait until the timeline passes the retire value
        // (same as Texture.Dispose)
        Device.EnqueueDeferredRelease(() =>
        {
            if (view.Handle != 0) vk.DestroyImageView(d, view, null);
            if (image.Handle != 0) vk.DestroyImage(d, image, null);
            if (memory.Handle != 0) vk.FreeMemory(d, memory, null);
        });
    }
}
