// Copyright (c) SeasonEngine and contributors.
// Licensed under the MIT License.
// https://github.com/SeasonRealms/SeasonEngine

using System.Runtime.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace Season.Utils;

/// <summary>
///Copy the semantic selection of members for the [DataContract] type by Newtonsoft. Johnson:
///When the type itself or any base class declares [DataContract], only members with [DataMember] are serialized/deserialized;
///The selection of default contracts for other members (public fields, read-only attributes, etc.) is determined by the caller's option set.
///For use with historical archive data generated by Newtonsoft. Johnson compatibility.
/// </summary>
public sealed class DataContractOptInResolver : IJsonTypeInfoResolver
{
    private readonly DefaultJsonTypeInfoResolver _inner = new DefaultJsonTypeInfoResolver();

    /// <inheritdoc/>
    public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)
    {
        JsonTypeInfo? typeInfo = _inner.GetTypeInfo(type, options);
        if (typeInfo == null)
        {
            return null;
        }

        if (HasDataContract(type))
        {
            IList<JsonPropertyInfo> properties = typeInfo.Properties;
            for (int i = properties.Count - 1; i >= 0; i--)
            {
                var provider = properties[i].AttributeProvider;
                if (provider != null && !provider.IsDefined(typeof(DataMemberAttribute), inherit: false))
                {
                    properties.RemoveAt(i);
                }
            }
        }

        return typeInfo;
    }

    /// <summary>
    ///Newtonsoft. Johnson searches upwards along the BaseType chain when determining [DataContract]
    ///(The Inherited value of DataMractAttribute is false and cannot depend on IsDefined (inherit: true)).
    /// </summary>
    private static bool HasDataContract(Type type)
    {
        for (Type? current = type; current != null && current != typeof(object); current = current.BaseType)
        {
            if (current.IsDefined(typeof(DataContractAttribute), inherit: false))
            {
                return true;
            }
        }
        return false;
    }
}
